# Generated by Django 5.2.4 on 2025-07-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('total_spend_today', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_spend_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_per_execution', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='budgetcontrol.brand')),
            ],
        ),
    ]
